### ISSUE TITLE
Unclear usage for NUnit TestCase

### ISSUE THREAD

**Issue by scottyearsley** [VerifyTests/Verify#678] opened 2022-10-19 16:58 UTC
I'm really struggling to understand how to use TestCase attributes [as documented here](https://github.com/VerifyTests/Verify/blob/main/docs/parameterised.md#testcase).

My test is using Bddfy alongside NUnit, with my test initialiser looking like this:

```cs
[TestCase((string)null!)]
[TestCase("")]
[TestCase("Some string which breaks the fifty character limit on names")]
public void Run(string invalidName)
{
    _invalidName = invalidName;
    this.BDDfy<CreateBookStory>();
}
```

The method to invoke Verify looks like the following:

```cs
[AndThen]
public Task AndThenTheRelevantValidationMessageIsReturned()
{
    return Verify(_validationErrorResponse);
}
```

I cannot figure out how I can pass a value to Verify to parameterise the test file name, which seems simple to do with other libraries with a `.UseParameters(arg)` call.

**Comment by SimonCropp** [comment] 2022-10-19 20:43
can u share the full class?

**Comment by SimonCropp** [comment] 2022-10-19 20:44
also what package are you using?

**Comment by SimonCropp** [comment] 2022-10-22 10:58
@scottyearsley  bump

**Comment by syearsley** [comment] 2022-10-23 08:54
Hi Simon, really sorry for not getting back to you sooner. 

Thankfully I have been able to figure out my issue and move on. Basically, I mistook an error coming out of Verify, which manifested as a `Duplicate item has already been added to the Dictionary` JSON serialization exception, to be an issue with the args I was passing in with the test cases and thought I was doing something wrong. I wondered if there was a clash of parameters I was sending in, i.e. null string and "" being seen mishandled.

However, it actually turned out to be an issue with the object under test itself (which is my type called `RestException`, i.e. `_validationErrorResponse` in my posted code) when it was being serialized using Verify's internal serializer. Interestingly this type serializes to a string using Newtonsoft happily, but not with `System.Text.Json`. I accepted that the issue is with my type so I mapped the values from it into an anonymous object and verified against that instead, so all good, so please close this issue.

Just want to say what a great library Verify is and how much cleaner and easier to write our acceptance tests are using it!

---
Just a thought, it would be really great if you could somehow specify an arg to be used for 'naming' the test case rather that the test value being used for the param of the received files. So something like:

```cs
[TestCase("Null string", (string)null!)]
[TestCase("Empty string", "")]
[TestCase("More than 50", "Some string which breaks the fifty character limit on names")]
public void Test(string testName, string testValue) 
{
    _testName = testName;
    _testValue = testValue
}
```

```cs
return Verify(_response, testName: _testName);
```

The received files could be clearer to read and potentially shorter - my example of "Some string which breaks the fifty character limit on names" is pretty long and I have an example where I pass in a string > 250 chars.

**Comment by SimonCropp** [comment] 2022-10-23 10:24
you can fully control all parts of the verified file name 

 * https://github.com/VerifyTests/Verify/blob/main/docs/naming.md
 * https://github.com/VerifyTests/Verify/blob/main/docs/parameterised.md#overriding-text-used-for-parameters

**Comment by syearsley** [comment] 2022-10-23 10:52
`UseTextForParameters()` is perfect, thank you 👍

**Closed** 2022-10-23 20:45 UTC
