### ISSUE TITLE
Verify conflicts with nunit test logger

### ISSUE THREAD

**Issue by MJB222398** [VerifyTests/Verify#1229] opened 2024-06-19 13:43 UTC
#### Describe the bug

My project is an NUnit test one that uses Verify. In my CI pipeline I use the dotnet CLI to run the test and make use of an NUnit logger (NunitXml.TestLogger NuGet package) with this. I updated Verify recently and this no longer works now in the case where a test fails as a result of a Verify action failing. If the test passes there is no problem - the test report is produced as expected. 

#### Minimal Repro

Test class: 

```
namespace VerifyLoggerBug
{
    public class Tests
    {
        [Test]
        public async Task Test1()
        {
            await Verify("gubbins", "txt");
        }
    }
}
```

Project file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="NUnit" Version="4.1.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="NunitXml.TestLogger" Version="3.1.20" />
    <PackageReference Include="Verify.NUnit" Version="25.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
```

Then run the test using the .NET CLI:

`dotnet test --configuration Release --verbosity minimal --logger:"html;LogFileName=TestResults.html" --logger:"trx;LogFileName=TestResults.trx;verbosity=detailed" --logger:"nunit;LogFileName=TestResults.xml;verbosity=detailed"`

If the test fails then inside the 'TestResults' directory I will see the .html and .trx files as expected but the nunit .xml file is not produced - instead I get a directory (called 'Username_MachineName_2024-06-19_14_27_30') that, inside several layers of sub directories, contains the '.received' verify file.

If you make the test pass then you get the expected .xml file instead.

This used to work in version 23.2.2 of Verify. I updated and now see the above issue. Have not updated the NunitXml.TestLogger dependency for a long time (as there have not been any) so that hasn't changed

**Comment by SimonCropp** [comment] 2024-06-20 08:58
as per the issue template

> Ensure you have replicated the bug in a minimal solution with the fewest moving parts. Often this will help point to the true cause of the problem. Upload this repro as part of the issue, preferably a public GitHub repository or a downloadable zip. The repro will allow the maintainers of this project to smoke test the any fix.

**Comment by MJB222398** [comment] 2024-06-20 10:38
[VerifyLoggerBug.zip](https://github.com/user-attachments/files/15912483/VerifyLoggerBug.zip)

See attached solution.  

To see the issue please run:

`dotnet test --configuration Release --verbosity minimal --filter UnitTestFailing --logger:"html;LogFileName=TestResults.html" --logger:"trx;LogFileName=TestResults.trx;verbosity=detailed" --logger:"nunit;LogFileName=TestResults.xml;verbosity=detailed"`

To see the report run correctly in the case that the test passes please run:

`dotnet test --configuration Release --verbosity minimal --filter UnitTestPassing --logger:"html;LogFileName=TestResults.html" --logger:"trx;LogFileName=TestResults.trx;verbosity=detailed" --logger:"nunit;LogFileName=TestResults.xml;verbosity=detailed"`

**Comment by SimonCropp** [comment] 2024-06-24 13:31
can u try 25.0.4

**Comment by MJB222398** [comment] 2024-06-24 20:38
@SimonCropp same issue I'm afraid. But it fixed it for you? Were you able to reproduce the issue before hand?

**Comment by SimonCropp** [comment] 2024-06-24 22:45
so u dont get the log file?

**Comment by MJB222398** [comment] 2024-06-25 08:46
@SimonCropp Correct, updating to 25.0.4 had zero effect. I still get this file instead of the .xml log file:

VerifyLoggerBug\TestResults\Username_MachineName_2024-06-24_21_31_30\In\8e84f204-73cf-4467-8842-a65ca0afebd2\MachineName\UnitTestFailing.TestFailing.received.txt

**Comment by SimonCropp** [comment] 2024-06-25 10:34
so what i fixed in 25.0.4 was that the test process was not exiting until the diff tool had been closed

the extra file is because Verify.Nunit now adds received files to nunit attachments https://github.com/VerifyTests/Verify/pull/1192 and that seems to result in them being copied to the test result log dir. As far as i can tell, that is acting as expected as per how nunit handles attachments. Verify cant control that behaviour

**Comment by MJB222398** [comment] 2024-06-25 11:05
OK if that directory is expected that is OK, just hadn't seen it until I updated Verify and it coincided with the .xml log file missing. So the expectation then is that I would get the .xml log file and the attached verify file in my TestResults directory.

Are you not able to reproduce the issue then?

So for clarity you don't think the update to Verify is what has caused the .xml log file to disappear? Or rather Verify has exposed the bug but  is not itself to blame. So it would be a bug in NUnit instead, or the logger library. I can raise with them and see what they say

**Comment by SimonCropp** [comment] 2024-06-25 11:34
sorry. i dont know why adding an nunit attachment prevents the log file from being created. i suggest you raise that with NunitXml.TestLogger project

**Comment by MJB222398** [comment] 2024-06-25 15:59
Have raised with them, they acknowledge its a bug at their end. The root cause being that they expected a description for any attachments. They are making a change so the description will be optional. 

If you are happy not having a description for the Verify attachments then I think this can be closed.

https://github.com/spekt/nunit.testlogger/issues/106

**Comment by SimonCropp** [comment] 2024-06-26 09:36
closing this since not a bug in Verify

**Closed by SimonCropp** 2024-06-26 09:36 UTC
